"""Finalize the demo: optional intro/outro concat + caption burn-in or sidecar.

Phase B step that runs AFTER `brand_video.py`. Phase A's brand_video handles
badge + waveform only; this step glues the intro/outro slides on either side
of the branded video and (optionally) burns captions in.

CLI:
    uv run scripts/finalize_video.py \
        --working-dir <path> --input <branded.mp4> --output <final.mp4>

Reads:
    <working_dir>/demo_config.yaml  (features.intro_slide, features.outro_slide,
                                     features.captions.{enabled,mode})
    <working_dir>/_intermediate/intro.mp4   (if intro_slide)
    <working_dir>/_intermediate/outro.mp4   (if outro_slide)
    <working_dir>/_voiceover/captions.srt   (if captions.enabled)

Writes:
    --output (final mp4)
    <output>.srt next to --output (if captions.mode == "srt-sidecar")

Approach: when caption burn-in is requested, captions are applied to the input
mp4 first (timing stays aligned with the SRT as-generated by make_captions.py).
Then intro + (input_with_captions or input) + outro are concatenated. When no
features are active, the input is byte-copied through unchanged.
"""
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
import argparse
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _lib import load_yaml, resolve_working_dir, ensure_dir

# Subtle white-on-dark caption style; bottom-center with a small margin.
# Alignment=2 = bottom-center in libass.
CAPTION_FORCE_STYLE = (
    "FontName=Helvetica,FontSize=22,"
    "PrimaryColour=&Hffffff,OutlineColour=&H000000,"
    "Outline=2,Shadow=0,Alignment=2,MarginV=40"
)


def burn_captions(input_path: Path, srt_path: Path, output_path: Path) -> None:
    """Re-encode video with subtitles=<srt> filter; audio is stream-copied.

    Homebrew's default `ffmpeg` formula omits libass; if subtitles filter
    isn't present, fail fast with a useful hint. Commas inside force_style
    must be backslash-escaped (they'd otherwise terminate the filter).
    """
    filters = subprocess.run(["ffmpeg", "-hide_banner", "-filters"],
                             capture_output=True, text=True).stdout
    if " subtitles " not in filters:
        sys.exit(
            "Your ffmpeg build lacks the `subtitles` filter (libass).\n"
            "macOS: `brew uninstall ffmpeg && brew install ffmpeg-full`.\n"
            "Or switch features.captions.mode to 'srt-sidecar' to ship the SRT alongside the mp4."
        )
    style = CAPTION_FORCE_STYLE.replace(",", r"\,")
    vf = f"subtitles=filename={srt_path}:force_style={style}"
    cmd = [
        "ffmpeg", "-y",
        "-i", str(input_path),
        "-vf", vf,
        "-c:v", "libx264", "-preset", "medium", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "copy",
        str(output_path),
    ]
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def concat_segments(segments: list[Path], output_path: Path, tmp_dir: Path) -> None:
    """ffmpeg concat demuxer with -c copy. Requires matching codec/fps/sr.

    make_intro_outro and brand_video both produce h264 + AAC 24kHz mono +
    same resolution + 25fps, so -c copy works.
    """
    list_file = tmp_dir / "concat_list.txt"
    list_file.write_text("\n".join(f"file '{p}'" for p in segments) + "\n")
    cmd = [
        "ffmpeg", "-y",
        "-f", "concat", "-safe", "0",
        "-i", str(list_file),
        "-c", "copy",
        str(output_path),
    ]
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def video_duration_seconds(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--working-dir", required=True)
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    wd = resolve_working_dir(args.working_dir)
    demo_config = load_yaml(wd / "demo_config.yaml")
    features = demo_config.get("features", {}) or {}
    want_intro = bool(features.get("intro_slide", False))
    want_outro = bool(features.get("outro_slide", False))
    captions_cfg = features.get("captions", {}) or {}
    captions_on = bool(captions_cfg.get("enabled", False))
    captions_mode = captions_cfg.get("mode", "burned")

    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    if not input_path.exists():
        sys.exit(f"Input not found: {input_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Default behavior: nothing to do → copy through.
    if not want_intro and not want_outro and not captions_on:
        shutil.copy(input_path, output_path)
        print(f"OK Finalized (pass-through): {output_path}")
        return

    intro_path = wd / "_intermediate" / "intro.mp4"
    outro_path = wd / "_intermediate" / "outro.mp4"
    srt_path = wd / "_voiceover" / "captions.srt"

    if want_intro and not intro_path.exists():
        sys.exit(f"features.intro_slide is on but {intro_path} is missing. "
                 "Run make_intro_outro.py first.")
    if want_outro and not outro_path.exists():
        sys.exit(f"features.outro_slide is on but {outro_path} is missing. "
                 "Run make_intro_outro.py first.")
    if captions_on and not srt_path.exists():
        sys.exit(f"features.captions.enabled is on but {srt_path} is missing. "
                 "Run make_captions.py first.")

    tmp_dir = ensure_dir(wd / "_intermediate" / "_finalize_tmp")

    # Step 1: optionally burn captions into a temp mid-segment.
    if captions_on and captions_mode == "burned":
        middle_path = tmp_dir / "input_with_captions.mp4"
        burn_captions(input_path, srt_path, middle_path)
    else:
        middle_path = input_path

    # Step 2: concat intro + middle + outro (skip any that aren't enabled).
    needs_concat = want_intro or want_outro
    if needs_concat:
        segments = []
        if want_intro:
            segments.append(intro_path)
        segments.append(middle_path)
        if want_outro:
            segments.append(outro_path)
        concat_segments(segments, output_path, tmp_dir)
    elif middle_path == input_path:
        # Captions-only with sidecar mode (no burn-in, no concat): copy through.
        # NB: never move/rename the input — it's the user's branded.mp4.
        shutil.copy(input_path, output_path)
    else:
        # Captions burned but no intro/outro: middle is the temp burned mp4.
        # Move it to the final location (safe; it's our own tmp file).
        shutil.move(str(middle_path), str(output_path))

    # Step 3: sidecar SRT (independent of burn-in path).
    if captions_on and captions_mode == "srt-sidecar":
        sidecar = output_path.with_suffix(output_path.suffix + ".srt")
        # Convention: <output>.srt next to <output>.mp4 (e.g. final.mp4.srt).
        # Avoids stomping a sibling file that happens to share the basename.
        shutil.copy(srt_path, sidecar)
        print(f"  Sidecar SRT: {sidecar}")

    duration = video_duration_seconds(output_path)
    size_mb = output_path.stat().st_size / 1_048_576
    print(f"OK Finalized: {output_path} ({size_mb:.1f} MB, {duration:.1f}s)")


if __name__ == "__main__":
    main()
