"""Finalize the demo: optional intro/outro concat + caption burn-in or sidecar.

Phase B step that runs AFTER `brand_video.py`. Phase A's brand_video handles
badge + waveform only; this step glues the intro/outro slides on either side
of the branded video and (optionally) burns captions in.

CLI:
    uv run scripts/finalize_video.py \
        --working-dir <path> --input <branded.mp4> --output <final.mp4>

Reads:
    <working_dir>/demo_config.yaml  (features.intro_slide, features.outro_slide,
                                     features.captions.{enabled,mode})
    <working_dir>/_intermediate/intro.mp4   (if intro_slide)
    <working_dir>/_intermediate/outro.mp4   (if outro_slide)
    <working_dir>/_voiceover/captions.srt   (if captions.enabled)

Writes:
    --output (final mp4)
    <output>.mp4.srt next to --output (if captions.mode == "srt-sidecar")

Approach: when caption burn-in is requested, captions are applied to the input
mp4 first (timing stays aligned with the SRT as-generated by make_captions.py).
Then intro + (input_with_captions or input) + outro are concatenated. When no
features are active, the input is byte-copied through unchanged.
"""
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _lib import load_yaml, resolve_working_dir, ensure_dir

# Defaults for the caption force_style. Branding.yaml's `captions.font_size`
# overrides DEFAULT_CAPTION_FONT_SIZE. The other knobs are not exposed —
# Outline=1 and MarginV=30 are sane regardless of font size.
#
# FontSize note: ffmpeg's subtitles filter converts SRT to ASS using a default
# PlayResY of 288. Text scales by (video_height / 288), so FontSize=10 on a
# 900-tall video renders ~31px (~3.5% of video height, typical professional
# subtitle size). Increase for emphasis, decrease for a denser look.
DEFAULT_CAPTION_FONT_SIZE = 10


def _caption_force_style(font_size: int) -> str:
    return (
        f"FontName=Helvetica,FontSize={font_size},"
        f"PrimaryColour=&Hffffff,OutlineColour=&H000000,"
        f"Outline=1,Shadow=0,Alignment=2,MarginV=30"
    )


def burn_captions(input_path: Path, srt_path: Path, output_path: Path,
                  tmp_dir: Path, font_size: int) -> None:
    """Re-encode video with subtitles=<srt> filter; audio is stream-copied.

    Homebrew's default `ffmpeg` formula omits libass; if subtitles filter
    isn't present, fail fast with a useful hint. Commas inside force_style
    must be backslash-escaped (they'd otherwise terminate the filter).

    Path-special chars (`:`, `\\`, `'`, `[`, `]`, `,`) in the SRT path would
    break the filter-graph parse, so we copy the SRT into tmp_dir and run
    ffmpeg with cwd=tmp_dir so the filter only needs a bare relative
    filename.
    """
    filters = subprocess.run(["ffmpeg", "-hide_banner", "-filters"],
                             capture_output=True, text=True).stdout
    # ffmpeg -filters output uses flag-prefix columns (e.g. " T.. ") and
    # variable whitespace, so we look for the name in column position
    # rather than relying on a fixed " subtitles " substring.
    if not re.search(r"^\s*\S+\s+subtitles\s", filters, re.MULTILINE):
        sys.exit(
            "Your ffmpeg build lacks the `subtitles` filter (libass).\n"
            "macOS: `brew uninstall ffmpeg && brew install ffmpeg-full`.\n"
            "Or switch features.captions.mode to 'srt-sidecar' to ship the SRT alongside the mp4."
        )
    local_srt = tmp_dir / "captions.srt"
    shutil.copy(srt_path, local_srt)
    style = _caption_force_style(font_size).replace(",", r"\,")
    vf = f"subtitles=filename={local_srt.name}:force_style={style}"
    cmd = [
        "ffmpeg", "-y",
        "-i", str(input_path),
        "-vf", vf,
        "-c:v", "libx264", "-preset", "medium", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "copy",
        str(output_path),
    ]
    print(" ".join(cmd))
    subprocess.run(cmd, check=True, cwd=tmp_dir)


def _build_xfade_filter(durations: list[float], crossfade_seconds: float) -> str:
    """Build the -filter_complex string for xfade + acrossfade across N segments.

    For N segments with durations d_0..d_{N-1} and crossfade D:
      Video chain: each xfade's offset = sum(d_0..d_{i-1}) - i*D
      Audio chain: acrossfade with duration D, triangular curves

    Returns the filter graph string. The caller pipes it into
    `ffmpeg -filter_complex` and maps [v]/[a] to the output.
    """
    n = len(durations)
    if n < 2:
        raise ValueError(f"xfade needs >= 2 segments, got {n}")
    if crossfade_seconds <= 0:
        raise ValueError(f"crossfade_seconds must be > 0, got {crossfade_seconds}")
    if crossfade_seconds >= min(durations):
        raise ValueError(
            f"crossfade_seconds={crossfade_seconds} must be less than the "
            f"shortest segment duration ({min(durations):.2f}s)"
        )

    d = crossfade_seconds
    video_parts: list[str] = []
    audio_parts: list[str] = []
    prev_v = "[0:v]"
    prev_a = "[0:a]"
    cum_offset = durations[0] - d
    for i in range(1, n):
        v_out = f"[v{i:02d}]" if i < n - 1 else "[v]"
        a_out = f"[a{i:02d}]" if i < n - 1 else "[a]"
        video_parts.append(
            f"{prev_v}[{i}:v]xfade=transition=fade:duration={d}:offset={cum_offset:.4f}{v_out}"
        )
        audio_parts.append(
            f"{prev_a}[{i}:a]acrossfade=d={d}:c1=tri:c2=tri{a_out}"
        )
        prev_v, prev_a = v_out, a_out
        if i < n - 1:
            cum_offset += durations[i] - d
    return ";".join(video_parts + audio_parts)


def _validate_crossfade_seconds(value) -> float:
    """Normalize and validate features.crossfade_seconds. Returns the float.

    Allowed: any non-negative number up to a hard cap of 2.0s. 0 = hard cuts
    (concat demuxer fast path). Negative, non-numeric, or > 2.0 -> exit with
    a clear error.
    """
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        sys.exit(f"features.crossfade_seconds must be a number, got {value!r}")
    v = float(value)
    if v != v:  # NaN
        sys.exit("features.crossfade_seconds must be a number, got NaN")
    if v < 0:
        sys.exit(f"features.crossfade_seconds must be >= 0, got {v}")
    if v > 2.0:
        sys.exit(
            f"features.crossfade_seconds capped at 2.0s, got {v}. "
            "Longer dissolves eat too much intro/outro content."
        )
    return v


def concat_segments(segments: list[Path], output_path: Path, tmp_dir: Path,
                    crossfade_seconds: float) -> None:
    """Concatenate segments into output_path.

    If crossfade_seconds == 0, uses ffmpeg's concat demuxer with -c copy
    (instant, no re-encode). If > 0, uses an xfade + acrossfade filter graph
    (re-encodes, ~30-60s for a 5-minute video, but produces soft seams).
    """
    if crossfade_seconds == 0:
        _concat_copy(segments, output_path, tmp_dir)
    else:
        _concat_xfade(segments, output_path, crossfade_seconds)


def _concat_copy(segments: list[Path], output_path: Path, tmp_dir: Path) -> None:
    """ffmpeg concat demuxer with -c copy. Requires matching codec/fps/sr.

    make_intro_outro and brand_video both produce h264 + AAC 24kHz mono +
    same resolution + 25fps, so -c copy works.
    """
    list_file = tmp_dir / "concat_list.txt"
    list_file.write_text("\n".join(f"file '{p}'" for p in segments) + "\n")
    cmd = [
        "ffmpeg", "-y",
        "-f", "concat", "-safe", "0",
        "-i", str(list_file),
        "-c", "copy",
        str(output_path),
    ]
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def _concat_xfade(segments: list[Path], output_path: Path,
                  crossfade_seconds: float) -> None:
    """Build a single ffmpeg -filter_complex call that chains xfade + acrossfade.

    Probes each segment's duration via ffprobe, then constructs the filter
    graph via `_build_xfade_filter`. Re-encodes with the same profile as
    brand_video.py.
    """
    durations = [video_duration_seconds(p) for p in segments]
    filter_graph = _build_xfade_filter(durations, crossfade_seconds)
    cmd = ["ffmpeg", "-y"]
    for seg in segments:
        cmd.extend(["-i", str(seg)])
    cmd.extend([
        "-filter_complex", filter_graph,
        "-map", "[v]", "-map", "[a]",
        "-c:v", "libx264", "-preset", "medium", "-crf", "20",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "192k",
        str(output_path),
    ])
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def video_duration_seconds(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--working-dir", required=True)
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    wd = resolve_working_dir(args.working_dir)
    demo_config = load_yaml(wd / "demo_config.yaml")
    branding = load_yaml(wd / "branding.yaml")
    features = demo_config.get("features", {}) or {}
    want_intro = bool(features.get("intro_slide", False))
    want_outro = bool(features.get("outro_slide", False))
    captions_cfg = features.get("captions", {}) or {}
    captions_on = bool(captions_cfg.get("enabled", False))
    captions_mode = captions_cfg.get("mode", "burned")
    # Validate mode early so typos (e.g. "burn", "sidecar") don't silently
    # drop captions despite captions.enabled: true.
    if captions_on and captions_mode not in ("burned", "srt-sidecar"):
        sys.exit(
            f"features.captions.mode must be 'burned' or 'srt-sidecar', "
            f"got {captions_mode!r}"
        )
    # crossfade_seconds defaults to 0.5 (polish by default). Set to 0 to
    # opt out and get the original -c copy concat fast path.
    crossfade_seconds = _validate_crossfade_seconds(
        features.get("crossfade_seconds", 0.5)
    )
    # Caption styling lives in branding.yaml. Only font_size is exposed for
    # now (Outline=1 and MarginV=30 are sane regardless).
    caption_font_size = int(
        (branding.get("captions", {}) or {}).get("font_size", DEFAULT_CAPTION_FONT_SIZE)
    )

    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    if not input_path.exists():
        sys.exit(f"Input not found: {input_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Default behavior: nothing to do → copy through.
    if not want_intro and not want_outro and not captions_on:
        shutil.copy(input_path, output_path)
        print(f"OK Finalized (pass-through): {output_path}")
        return

    intro_path = wd / "_intermediate" / "intro.mp4"
    outro_path = wd / "_intermediate" / "outro.mp4"
    srt_path = wd / "_voiceover" / "captions.srt"

    if want_intro and not intro_path.exists():
        sys.exit(f"features.intro_slide is on but {intro_path} is missing. "
                 "Run make_intro_outro.py first.")
    if want_outro and not outro_path.exists():
        sys.exit(f"features.outro_slide is on but {outro_path} is missing. "
                 "Run make_intro_outro.py first.")
    if captions_on and not srt_path.exists():
        sys.exit(f"features.captions.enabled is on but {srt_path} is missing. "
                 "Run make_captions.py first.")

    tmp_dir = ensure_dir(wd / "_intermediate" / "_finalize_tmp")

    try:
        # Step 1: optionally burn captions into a temp mid-segment.
        if captions_on and captions_mode == "burned":
            middle_path = tmp_dir / "input_with_captions.mp4"
            burn_captions(input_path, srt_path, middle_path, tmp_dir, caption_font_size)
        else:
            middle_path = input_path

        # Step 2: concat intro + middle + outro (skip any that aren't enabled).
        needs_concat = want_intro or want_outro
        if needs_concat:
            segments = []
            if want_intro:
                segments.append(intro_path)
            segments.append(middle_path)
            if want_outro:
                segments.append(outro_path)
            concat_segments(segments, output_path, tmp_dir, crossfade_seconds)
        elif middle_path == input_path:
            # Captions-only with sidecar mode (no burn-in, no concat): copy through.
            # NB: never move/rename the input — it's the user's branded.mp4.
            shutil.copy(input_path, output_path)
        else:
            # Captions burned but no intro/outro: middle is the temp burned mp4.
            # Copy (not move) since tmp_dir is removed in the finally block.
            shutil.copy(str(middle_path), str(output_path))

        # Step 3: sidecar SRT (independent of burn-in path).
        if captions_on and captions_mode == "srt-sidecar":
            sidecar = output_path.with_suffix(output_path.suffix + ".srt")
            # Convention: <output>.mp4.srt next to <output>.mp4. Keeps the
            # full video filename in the sidecar so a sibling file sharing
            # the basename (e.g. final.srt from a different run) isn't
            # silently stomped.
            shutil.copy(srt_path, sidecar)
            print(f"  Sidecar SRT: {sidecar}")

        duration = video_duration_seconds(output_path)
        size_mb = output_path.stat().st_size / 1_048_576
        print(f"OK Finalized: {output_path} ({size_mb:.1f} MB, {duration:.1f}s)")
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
